import { serve } from "https://deno.land/std@0.224.0/http/server.ts";
import { handleCors, json } from "../_shared/cors.ts";
import { requireUser } from "../_shared/auth.ts";
import { sha256Hex } from "../_shared/otp.ts";

const PURPOSES = ["consent", "contact", "intercept", "visit"] as const;
type OtpPurpose = (typeof PURPOSES)[number];

// Must mirror the code generated by auth-otp: purpose + ":" + sha256(profileId:purpose:code).
async function challengeHash(
  profileId: string,
  purpose: OtpPurpose,
  code: string
): Promise<string> {
  return `${purpose}:${await sha256Hex(`${profileId}:${purpose}:${code}`)}`;
}

serve(async (req) => {
  const cors = handleCors(req);
  if (cors) return cors;
  if (req.method !== "POST") {
    return json({ error: "Method not allowed" }, 405);
  }

  // The gateway enforces verify_jwt = true, but we double-check the token so
  // the function is safe even if it is ever exposed without JWT verification.
  const { ctx, error } = await requireUser(req);
  if (error) return error;

  const body = await req.json().catch(() => null);
  if (!body) {
    return json({ error: "Invalid JSON body" }, 400);
  }

  const { purpose, phone, code } = body as {
    purpose?: string;
    phone?: string;
    code?: string;
  };
  if (!PURPOSES.includes(purpose as OtpPurpose)) {
    return json({ error: "Invalid purpose" }, 400);
  }
  // The phone is accepted for audit symmetry with auth-otp but the code is
  // bound to (profile, purpose) alone, so it is not used for matching.
  if (typeof phone !== "undefined" && typeof phone !== "string") {
    return json({ error: "Invalid phone number" }, 400);
  }
  if (typeof code !== "string" || !/^\d{6}$/.test(code)) {
    return json({ error: "Invalid code" }, 400);
  }

  const { data: settings } = await ctx.db
    .from("app_settings")
    .select("key, value")
    .eq("key", "otp.max_attempts")
    .maybeSingle();
  const configured = Number(settings?.value ?? 5);
  const maxAttempts = Number.isFinite(configured) && configured > 0
    ? configured
    : 5;

  // Look up the LATEST unconsumed challenge for this profile+purpose, then
  // compare the computed hash directly — no plaintext is ever stored.
  const candidate = await challengeHash(ctx.profile.id, purpose as OtpPurpose, code);
  const { data: challenge, error: fetchError } = await ctx.db
    .from("auth_otp_challenges")
    .select("id, code_hash, attempts, expires_at, consumed_at")
    .eq("profile_id", ctx.profile.id)
    .like("code_hash", `${purpose}:%`)
    .is("consumed_at", null)
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();
  if (fetchError) {
    return json({ error: fetchError.message }, 500);
  }

  if (!challenge) {
    return json({ ok: false, error: "Invalid or expired code" }, 401);
  }

  const wrongCode = challenge.code_hash !== candidate;
  const expired = new Date(challenge.expires_at).getTime() <= Date.now();
  const outOfAttempts = challenge.attempts >= maxAttempts;
  if (wrongCode || expired || outOfAttempts) {
    // Burn one attempt even on a wrong/expired code so brute force is bounded.
    await ctx.db
      .from("auth_otp_challenges")
      .update({ attempts: challenge.attempts + 1 })
      .eq("id", challenge.id);
    return json({ ok: false, error: "Invalid or expired code" }, 401);
  }

  await ctx.db
    .from("auth_otp_challenges")
    .update({ consumed_at: new Date().toISOString() })
    .eq("id", challenge.id);

  // The proof object is the compliance record that a real interaction
  // (consent/contact/intercept/visit) happened at the outlet.
  return json({
    ok: true,
    verified: true,
    proof: {
      challenge_id: challenge.id,
      purpose,
      verified_at: new Date().toISOString(),
    },
  });
});